services:
  - type: web
    name: dashboard-leiloes
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard_leiloes:server --bind 0.0.0.0:$PORT
